name: SonarCloud Trigger

on: 
  push: 
    branches:
    - 'master'
    - 'dev-alpha'
    - 'dev-beta'
    - 'dev-gama'
    - 'dev-delta'
    paths:
    - 'backend/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  
  sonarCloudTrigger:
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Analyses with SonarCloud
        uses: sonarsource/sonarcloud-github-action@v1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
