version: "3.8"

services:
    db:
        image: postgres
        container_name: dev8-db
        environment:
          POSTGRES_PASSWORD: root
        volumes: 
            - /home/postgres:/var/lib/postgresql
        ports:
          - "5432:5432"
        networks:
          - db
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        restart: always
        networks: 
            - broker-kafka
        environment:
            JVMFLAGS: -Xmx70m
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
    kafka:
        container_name: kafka
        image: confluentinc/cp-kafka:latest
        networks: 
            - broker-kafka
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
        environment:
            KAFKA_HEAP_OPTS: -Xmx512M -Xms512M
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    email:
        depends_on: 
            - kafka
        image: 334077612733.dkr.ecr.sa-east-1.amazonaws.com/dev8/email:aws
        networks:
            - broker-kafka
    backend:
        depends_on: 
            - db
        image: 334077612733.dkr.ecr.sa-east-1.amazonaws.com/dev8/backend:aws
        environment:
            SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/postgres"
        volumes:
            - ./home/uploads:/app/uploads:cached
        networks:
            - broker-kafka
            - db
            - backend
    backend-chat:
        image: 334077612733.dkr.ecr.sa-east-1.amazonaws.com/dev8/websocket:aws
        networks:
            - backend-chat
            - broker-kafka
            - db
    nginx:
        depends_on:
            - backend
            - backend-chat
        image: 334077612733.dkr.ecr.sa-east-1.amazonaws.com/dev8/front:aws
        networks:
            - backend
            - backend-chat
            - nginx
        ports:
            - "80:80"
networks:
    broker-kafka:
    backend:
    db:
    backend-chat:
    nginx: