server:
  error:
    include-stacktrace: on-param

spring:
  #  Um limitador de tamanho de imagem em @Multipart.
  #  servlet:
  #    multipart:
  #      max-file-size: 128KB
  #      max-request-size: 128KB
#  flyway:
#    locations: classpath:db/migration/common
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true

  datasource:
    hikari:
      connectionTimeout: 1000
      maximumPoolSize: 10
    url: jdbc:postgresql:postgres
    username: postgres
    password: root

jwt:
  secret: d7af8aaa86594228f705d5b4ccc18cfa
  expiration: 86400000

kafka.bootstrap-servers:
  kafka:9092